{{- include "agenthive.validate" . -}}
{{- if and (eq .Values.database.type "postgres") (not .Values.database.postgres.existingSecret) (.Values.database.postgres.url) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agenthive.fullname" . }}-database
  labels:
    {{- include "agenthive.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.postgres.url | quote }}
{{- end }}
---
{{- if and (not .Values.redis.existingSecret) (.Values.redis.url) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agenthive.fullname" . }}-redis
  labels:
    {{- include "agenthive.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-url: {{ .Values.redis.url | quote }}
{{- end }}
---
{{- if and .Values.auth.azureAd.enabled (not .Values.auth.azureAd.existingSecret) (.Values.auth.azureAd.clientSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agenthive.fullname" . }}-azure-ad
  labels:
    {{- include "agenthive.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.auth.azureAd.clientSecret | quote }}
{{- end }}
